version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    links:
      - db:db
    environment:
      PGRST_DB_URI: postgres://app_user:password@db:5432/at_uconn
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: app_user

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "./docker/postgres/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: at_uconn
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
